events {}

http {
  server {
    listen 80;

    location /auth/ {
  proxy_pass http://auth-service:3001/;
}

    location /patients/ {
      proxy_pass http://patient-service:3002/patients/;
    }

    location /doctors/ {
      proxy_pass http://doctor-service:3003/doctors/;
    }

    location /appointments/ {
      proxy_pass http://appointment-service:3004/appointments/;
    }

    location /billing/ {
      proxy_pass http://billing-service:3005/billing/;
    }
  }
}